server:
  port:
    8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO

spring:
  main:
    allow-circular-references: true
  application:
    name: api-gateway

url:
  security: http://localhost:8083/

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka