server:
  port:
    8085

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee
          uri: lb://EMPLOYEE
          predicates:
            - Path=/**

        - id: security
          uri: lb://SECURITY
          predicates:
            - Path=/**

        - id: defect
          uri: lb://DEFECT
          predicates:
            - Path=/**

#      discovery:
#        locator:
#          enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka