server:
  port: 8085

spring:
  application:
    name: notification

  datasource:
    url: jdbc:postgresql://localhost:5434/cvqs
    username: efe
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

notification:
  defect:
    queue: notification_terminal_queue
    exchange: notification_terminal_exchange
    routingKey: notification_terminal_routing_key